### PR TITLE
make it compile

### PR DESCRIPTION
**Pull request by ShakalnyKot**
# Pull request

I slightly modified `Cargo.toml` by commenting out crates that does not allowed it to compile.

Affected crates:
- crate
- fuck

##### Fill either one
- [ ] Does your pull request add a crate?
- [ ] Does your pull request add a new language?

- [X] Is your pull request memory safe?
- [X] Is your pull request configurable?
- [X] Is your pull request minimal?
- [X] Is your pull request blazing fast?

### CODE REVIEW

**Comment by rozbrajaczpoziomow** [comment]
As per CONTRIBUTING.md, please add a new crate if you're making a PR. :)

**Comment by ShakalnyKot** [comment]
I poked some crates from crates.io, and building them requires some regex-related crates which are cannot be built on the Rust toolchain version that this project currently has. Update Rust toolchain version?

**Comment by rozbrajaczpoziomow** [comment]
> Update Rust toolchain version?
Feel free to update the toolchain version if needed.

> I added a bit of crates, and it now requires 1240 crates. However, u2f crate has been sacrificed for that.
That's probably fine, just remember to update the count in the README.

> Also, I suggest archive the non-modified version of the project to the read-only branch called, for example, archive.
Good idea, I shall do that.

**Comment by rozbrajaczpoziomow** [comment]
Looks good to merge then. I won't even try to compile this to see if it works...for obvious reasons.

**Pull request merged**
